config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  devise_scope :user do
    root "devise/sessions#new"
  end

  post 'search', to: 'currencies#search'
  post 'calculate', to: 'currencies#calculate'

  resources :users

  resources :currencies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency.rb
class Currency < ApplicationRecord
  def calculate_value(amount)
    (current_price.to_f * amount.to_f).round(0)
  end

  def current_price
    url = "https://pro-api.coinmarketcap.com/v2/cryptocurrency/quotes/latest?slug=#{self.slug}&convert=JPY"
    request = HTTParty.get(url, headers: { "X-CMC_PRO_API_KEY" => Rails.application.credentials[:coinAPI] })
    JSON.parse(request.body)['data'].values[0]['quote']['JPY']['price']
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(user)
    currencies_path
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # skip_before_action :authenticate_user!

  def search
    @currencies = Currency.where('LOWER(name) LIKE ?', "%#{params[:search].downcase}%")
    render json: { currencies: @currencies }
  end

  # takes currency id and amount owned, returning final calculation
  def calculate
    amount = params[:amount]
    render json: {
      currency: currency,
      current_price: currency.current_price,
      amount: amount,
      value: currency.calculate_value(amount)
    }
  end

  private

  def currency
    @currency ||= Currency.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/currencies/index.html.erb
<%= javascript_pack_tag 'index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoPortfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  </body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_log_in.erb
<%= link_to "Login", new_user_session_path, class: "login", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
<div class="sign-in-box dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
  <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), data: { turbo: :false }) do |f| %>
    <div class="form-inputs">
      <%= f.input :email, required: false, autofocus: true, input_html: { autocomplete: "email" } %>
      <%= f.input :password, required: false, input_html: { autocomplete: "current-password" } %>
      <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
      <div class="forgot-pw">
        <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
          <%= link_to "Forgot your password?", new_password_path(resource_name), class:"crypto-text" %><br />
        <% end %>
      </div>
    </div>
    <div class="crypto-button">
      <%= f.button :submit, "Log in", class: "crypto-text" %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-crypto">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <h1>Cryptolio</h1>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%= render "shared/signed_in" %>
        <% else %>
          <%= render "shared/log_in" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_signed_in.erb
<li class="user-name">
  <p>Welcome, <%= current_user.name %>!</p>
</li>
<li class="logout-button">
  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"crypto-text" %>
</li>